// <auto-generated />
namespace TrocCommunity.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProblemContext_MdodifBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProblemContext_MdodifBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181726312_ProblemContext_MdodifBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
