// <auto-generated />
namespace TrocCommunity.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class noLimitPassWord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noLimitPassWord));
        
        string IMigrationMetadata.Id
        {
            get { return "202102221604568_noLimitPassWord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
